name: fita
version: 0.0.1
apiVersion: v2
description: a Helm chart to manage constrained IoT devices using Kubernetes and NextGenGW
dependencies:
- name: far-edge-node-watcher
  version: 0.0.4
  repository: oci://ghcr.io/fraunhoferportugal/fita/charts
- name: far-edge-connection-provisioner
  version: 0.0.2
  repository: oci://ghcr.io/fraunhoferportugal/fita/charts
- name: nextgengw
  version: 0.1.0
  repository: oci://ghcr.io/fraunhoferportugal/fita/charts
appVersion: 0.0.0
