apiVersion: v1
kind: Service
metadata:
  name: fita-tig-grafana-ext
spec:
  selector:
    app.kubernetes.io/name: grafana
  ports:
    - protocol: TCP
      port: 3000
      nodePort: 30101
      name: "grafana-external"
  type: NodePort