TemperatureSensorDataImage:
  pullPolicy: IfNotPresent
  repository: ghcr.io/fraunhoferportugal/fita/demos/temperature-monitoring/components/simple-sensor-data-collector
  tag: 0.1.0

  mqttUrl: mqtt-broker
  mqttPort: 1883
  mqttClientId: simple-sensor-data-collector
  telegrafUrl: fita-tig-telegraf
  telegrafPort: 8126