nodes:
  node1:
    type: 'zephyr'
    image: 'images/embserve.elf'
    bootstrap:
      - 'embserve connector lwm2m server_add coap://10.10.12.254:5683 node1'
    networks:
      linux-br:
        ipv4_address: 10.10.12.1
        ipv4_gateway: 10.10.12.254

  node2:
    type: 'zephyr'
    image: 'images/embserve.elf'
    bootstrap:
      - 'embserve connector lwm2m server_add coap://10.10.12.254:5683 node2'
    networks:
      linux-br:
        ipv4_address: 10.10.12.2
        ipv4_gateway: 10.10.12.254

# applications:
#   proxy:
#     type: 'native'
#     image: 'socat UDP4-LISTEN:5683,fork,so-bindtodevice=lnxbr-0,reuseaddr UDP4:172.16.5.30:30009'

networks:
  linux-br:
    type: 'linux-br'
    host_address: 10.10.12.254
