name: Bump, tag and release main
on:
  pull_request:
    types: [closed]
    branches:
      - main

  workflow_dispatch:
    inputs:
      bump:
        type: string
        default: none
        required: true
        description: "The type of bump to use in the tag"

permissions:
  contents: write
  pull-requests: read
  packages: write

jobs:
  check-skip:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      skip-tag: ${{ steps.check.outputs.skip-tag }}
    steps:
      - name: Check PR labels and target branch
        id: check
        run: |
          TARGET_BRANCH=$(jq -r .pull_request.base.ref $GITHUB_EVENT_PATH)
          PR_LABELS=$(jq -r '.pull_request.labels[].name' $GITHUB_EVENT_PATH || echo "")
          echo "Target branch: $TARGET_BRANCH"
          echo "PR labels: $PR_LABELS"

          if [ "$TARGET_BRANCH" != "main" ] || echo "$PR_LABELS" | grep -q "no-tag"; then
            echo "skip-tag=true" >> $GITHUB_OUTPUT
          else
            echo "skip-tag=false" >> $GITHUB_OUTPUT
          fi

  bump-and-tag:
    name: Bump and tag FITA version
    runs-on: ubuntu-latest
    needs: check-skip
    if: ${{ always() && (github.event_name == 'workflow_dispatch' || (needs.check-skip.result == 'success' && needs.check-skip.outputs.skip-tag == 'false')) }}
    outputs:
      new-tag: ${{ steps.tag.outputs.new-tag }}
    steps:
      - name: Install RelSync
        run: pip install git+https://github.com/fraunhoferportugal/RelSync.git@main --break-system-packages

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: website/package-lock.json

      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: main

      - run: |
          git tag -l | xargs -r git tag -d
          git fetch --tags origin

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Determine bump type from PR comments
        id: bump
        if: github.event.pull_request.merged == true
        run: |
          comments=$(gh api repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
            --jq 'sort_by(.created_at) | reverse | .[].body')
      
          app_bump="none"
          # Regex:
          # !relsync bump (major|minor|patch)
          while IFS= read -r comment; do
            if [[ "$comment" =~ !relsync[[:space:]]+bump[[:space:]]+(major|minor|patch|release) ]]; then
              bump="${BASH_REMATCH[1]}"
              app_bump="$bump"

              break
            fi
          done <<< "$comments"
      
          echo "app-bump=$app_bump" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Compute new tag
        id: tag
        env:
          APP_BUMP: ${{ steps.bump.outputs.app-bump }}
        run: ./.github/scripts/compute-tag.sh
        
      - name: Update Documentation
        if: ${{ steps.tag.outputs.new-tag != 'skipped' }}
        working-directory: ./website
        run: |
          MAJOR_VERSION=$(echo "${{ steps.tag.outputs.new-tag }}" | cut -d. -f1)
          echo "MAJOR_VERSION=$MAJOR_VERSION"
          VERSIONED_DIR="./versioned_docs/version-${MAJOR_VERSION}.x"

          if [ ! -d "$VERSIONED_DIR" ]; then
              echo "Versioned docs do not exist. Creating..."
              npm ci
              npm run docusaurus docs:version "${MAJOR_VERSION}.x"
              echo "Created versioned docs at $VERSIONED_DIR"
          else
              exit 0
          fi

          git add .
          git commit -m "Create versioned documentation for version \"${MAJOR_VERSION}.x\""
          git push origin ${{ github.event.pull_request.head.ref }}

      - name: Create and push tag
        if: ${{ steps.tag.outputs.new-tag != 'skipped' }}
        run: |
          relsync bump ${{ steps.tag.outputs.new-tag }} \
            --chart-bump-type ${{ steps.tag.outputs.new-tag }} \
            --commit \
            --create-tag \
            -o json

          git push
          git push origin ${{ steps.tag.outputs.new-tag }}

  release:
    needs: bump-and-tag
    if: ${{ always() && needs.bump-and-tag.result == 'success' && needs.bump-and-tag.outputs.new-tag != 'skipped' }}
    uses: ./.github/workflows/release.yaml
    with:
      tag: ${{ needs.bump-and-tag.outputs.new-tag }}

  sync-development:
    name: Sync development branch
    needs: ["release", "bump-and-tag"]
    if: ${{ always() && needs.release.result == 'success'}}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: development

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge main into development
        run: |
          git fetch origin main
          git merge --no-ff origin/main -m "Merge main into development after release ${{ needs.bump-and-tag.outputs.new-tag }}" || true

      - name: Push changes
        run: |
          git push origin development

  deploy-documentation:
    name: Deploy Documentation
    needs: ["release", "bump-and-tag"]
    if: ${{ always() && needs.release.result == 'success'}}
    uses: ./.github/workflows/deploy-docs.yaml
