# name: Docs build test

# on:
#   pull_request:
#     branches:
#       - main
#       - development

# jobs:
#   test-deploy:
#     name: Test deployment
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#         with:
#           fetch-depth: 0
#       - uses: actions/setup-node@v4
#         with:
#           node-version: 22
#           cache: npm
#         decide if needs new version
#
#       - name: Install dependencies
#         run: npm ci
#       - name: Test build website
#         run: npm run build
