name: Update component releases

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch: {}

jobs:
  sync:
    runs-on: self-hosted
    permissions:
      contents: write
    outputs:
      relsync-output: ${{ steps.relsync.outputs.output }}
    steps:
      - name: Install RelSync
        run: pip install git+https://github.com/fraunhoferportugal/RelSync.git@main

      - name: Checkout main branch
        uses: actions/checkout@v6
        with:
          ref: main
          submodules: true

      - name: Configure committer info
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Create/Reset the update branch and switch to it
        run: |
          git switch -C relsync/releases
      
      - name: Fetch new submodules and commit with updated tags and Chart
        id: relsync
        run: |
          output=$(relsync update --commit --output json)
          echo "$output"

          changed=$(echo "$output" | jq -r '.committed_changes')
          echo "changed=$changed" >> $GITHUB_OUTPUT
          echo "output=$output" >> $GITHUB_OUTPUT
      
      - name: Push changes
        if: ${{ steps.relsync.outputs.changed == 'true' }}
        run: git push origin relsync/releases --force-with-lease
      
  create-pr:
    name: Create submodule update PR
    runs-on: self-hosted
    permissions:
      contents: write
      pull-requests: write
      issues: write
    needs: sync
    steps:
      - name: Install RelSync
        run: pip install git+https://github.com/fraunhoferportugal/RelSync.git@main

      - name: Checkout main branch
        uses: actions/checkout@v6

      - name: Create PR for submodule update branch
        id: create-pr
        uses: peter-evans/create-pull-request@v7
        with:
          base: main
          title: "[relsync] Update submodule releases"
          labels: |
            bot-pr
            release
          body: "Automated PR generated by relsync to update submodule pointers to latest releases."
          branch: relsync/releases
          delete-branch: true

      - name: Create message
        id: create-message
        run: |
          message=$(echo "${{ needs.sync.outputs.relsync-output }}" | relsync format -o comment)
          echo "message=$message" >> $GITHUB_OUTPUT

          changed=$(echo "$output" | jq -r '.committed_changes')
          echo "changed=$changed" >> $GITHUB_OUTPUT

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v5
        if: steps.create-message.outputs.changed == 'true'
        with:
          issue-number: ${{ steps.create-pr.outputs.pull-request-number }}
          body: |
            ${{ steps.create-message.outputs.message }}
