{{- if .Values.mqttBroker.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mqtt-broker
spec:
  selector:
    app: {{ template "fita.fullname" . }}-mqtt-broker
  ports:
    - protocol: TCP
      port: {{ .Values.mqttBroker.containerPort }}
      nodePort: {{ .Values.mqttBroker.nodePort }}
      name: "mqtt"
  type: NodePort
{{- end }}